parameters:
  - name: AzureRMServiceConnection # name of the Service Connection
    type: string
  - name: AzureRMServiceConnectiontfState
    type: string
  - name: storage_account_resource_group_name # The name of the resource group which contains the storage account selected below
    type: string
    default: "rg-TerraformBackend-01"
  - name: backendAzureRmUseEntraIdForAuthentication
    type: boolean
    default: false
  - name: azureRmUseIdTokenGeneration # In AzureRm version >3.80 it is needed to be set to true
    type: boolean
    default: false
  - name: storage_account_name # The name of the storage account which contains the Azure Blob container selected below.
    type: string
  - name: container_name # The name of the Azure Blob container in which to store the Terraform remote state file.
    type: string
  - name: key # The path to the Terraform remote state file inside the container. For example, if you want to store the state file, named terraform.tfstate, inside a folder, named tf, then give the input 'tf/terraform.tfstate'
    type: string
  - name: variables
    type: object
    default: {}
  - name: terraformVersion # The Version number of terraform to install
    type: string
    default: "1.1.2"
  - name: commandOptions # additional arguments for terraform plan and apply
    type: string
    default: ""
  - name: commandOptionsInit # additional arguments for terraform init
    type: string
    default: ""
  - name: workingDirectory # Folder with terraform files
    type: string
    default: "$(System.DefaultWorkingDirectory)"
  - name: environment #name of the envorenment to use - should only contain [A-Za-z0-9] or underscores, dashes, spaces as used as stage id
    type: string
  - name: initStepsPlan #steps to run before init in each plan stage probably only runs fine when using DefaultWorkingDirectory as workingDirectory
    type: stepList
    default: []
  - name: initStepsApply #steps to run before init in each apply stage probably only runs fine when using DefaultWorkingDirectory as workingDirectory
    type: stepList
    default: []
  - name: beforePlanJobs
    type: jobList
    default: []
  - name: beforeDeployJobs
    type: jobList
    default: []
  - name: afterDeployJobs
    type: jobList
    default: []
  - name: allowedBranches #List of branches to allow deployment from
    type: object
    default:
      - "refs/heads/master"
      - "refs/heads/main"
  - name: preApplySteps
    type: stepList
    default: []
  - name: useCLIApply
    type: boolean
    default: false
  - name: afterApplySteps #steps run after terraform apply
    type: stepList
    default: []
  - name: repository
    type: string
  - name: timeoutInMinutes 
    type: number
    default: 60
  - name: templateVariables
    type: object
    default: {}
  - name: planDependsOnStage
    type: string
    default: ''

stages:
  - stage: "Plan${{ replace(replace(parameters.environment, '-','_'),' ','_') }}"
    ${{ if ne(parameters.planDependsOnStage, '') }}:
      dependsOn: ${{ parameters.planDependsOnStage }}
    displayName: "${{ parameters.environment }} - Plan Deployment"
    condition: not(or(failed(), canceled()))
    ${{ if ne(length(parameters.templateVariables), 0) }}:
      variables:
        ${{ each pair in parameters.templateVariables }}:
          ${{ pair.key }}: ${{ pair.value }}
    jobs:
      - ${{ parameters.beforePlanJobs }}
      - job: Plan
        timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
        steps:
          - checkout: ${{ parameters.repository}}
            path: terraform
          - checkout:  iacwh-template-pipelines
            path: config
          - task: PowerShell@2
            displayName: Copy Config
            inputs:
              targetType: 'inline'
              script: |
                tree ..
                Get-ChildItem -Path ".." -Recurse | select *
                Copy-Item -Path ../config/* -Destination ${{ parameters.workingDirectory }} -Include *.tfvars
                Copy-Item -Path ../terraform/* -Destination ${{ parameters.workingDirectory }} -Recurse
                Get-ChildItem ${{ parameters.workingDirectory }} -Recurse | select *
              failOnStderr: true
          - ${{ parameters.initStepsPlan }}
          - template: steps/terraform-init.yml
            parameters:
              AzureRMServiceConnection: ${{ parameters.AzureRMServiceConnectiontfState }}
              storage_account_resource_group_name: ${{ parameters.storage_account_resource_group_name }}
              terraformVersion: ${{ parameters.terraformVersion }}
              storage_account_name: ${{ parameters.storage_account_name }}
              container_name: ${{ parameters.container_name }}
              key: ${{ parameters.key }}
              workingDirectory: ${{ parameters.workingDirectory }}
              commandOptions: "${{ parameters.commandOptionsInit }}"
              backendAzureRmUseEntraIdForAuthentication: ${{ parameters.backendAzureRmUseEntraIdForAuthentication }}
              backendAzureRmUseIdTokenGeneration: ${{ parameters.azureRmUseIdTokenGeneration }}
          - template: steps/terraform-plan.yml
            parameters:
              AzureRMServiceConnection: ${{ parameters.AzureRMServiceConnection }}
              variables: ${{ parameters.variables }}
              workingDirectory: ${{ parameters.workingDirectory }}
              commandOptions: "-out=tfplan ${{ parameters.commandOptions }}"
              environmentAzureRmUseIdTokenGeneration: ${{ parameters.azureRmUseIdTokenGeneration }}
          # archive files to preserve permissions (https://github.com/microsoft/azure-pipelines-tasks/issues/6364)
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: ${{ parameters.workingDirectory }}
              includeRootFolder: false
              archiveType: "tar"
              archiveFile: "$(Build.ArtifactStagingDirectory)/QBYND.tar.gz"
              replaceExistingArchive: true
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: ${{ parameters.environment }}

  - stage: "Deploy${{ replace(replace(parameters.environment, '-','_'),' ','_') }}"
    displayName: "${{ parameters.environment }} - Deploy"
    dependsOn: "Plan${{ replace(replace(parameters.environment, '-','_'),' ','_') }}"
    condition: and(succeeded(), or(${{ containsValue(parameters.allowedBranches,variables['Build.SourceBranch']) }}, eq(${{ length(parameters.allowedBranches)  }},0)))
    jobs:
      - '${{ parameters.beforeDeployJobs }}'
      - deployment: Deploy
        timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                #Use download task (https://github.com/microsoft/azure-pipelines-tasks/issues/11267)
                - download: none
                - ${{ parameters.initStepsApply }}
                - task: DownloadPipelineArtifact@2
                  displayName: "Download Plan"
                  inputs:
                    source: current
                    artifactName: ${{ parameters.environment }}
                    targetPath: $(Build.ArtifactStagingDirectory)
                - task: ExtractFiles@1
                  inputs:
                    archiveFilePatterns: "$(Build.ArtifactStagingDirectory)/QBYND.tar.gz"
                    destinationFolder: "$(System.DefaultWorkingDirectory)"
                    cleanDestinationFolder: false
                - template: steps/terraform-init.yml
                  parameters:
                    AzureRMServiceConnection: ${{ parameters.AzureRMServiceConnectiontfState }}
                    storage_account_resource_group_name: ${{ parameters.storage_account_resource_group_name }}
                    terraformVersion: ${{ parameters.terraformVersion }}
                    storage_account_name: ${{ parameters.storage_account_name }}
                    container_name: ${{ parameters.container_name }}
                    key: ${{ parameters.key }}
                    workingDirectory: "$(System.DefaultWorkingDirectory)"
                    commandOptions: "${{ parameters.commandOptionsinit }}"
                    backendAzureRmUseEntraIdForAuthentication: ${{ parameters.backendAzureRmUseEntraIdForAuthentication }}
                    backendAzureRmUseIdTokenGeneration: ${{ parameters.azureRmUseIdTokenGeneration }}
                - ${{ parameters.preApplySteps }}
                - ${{ if eq(parameters.useCLIApply, false) }}:
                  - template: steps/terraform-apply.yml
                    parameters:
                      AzureRMServiceConnection: ${{ parameters.AzureRMServiceConnection }}
                      workingDirectory: "$(System.DefaultWorkingDirectory)"
                      commandOptions: "${{ parameters.commandOptions }} tfplan"
                      environmentAzureRmUseIdTokenGeneration: ${{ parameters.azureRmUseIdTokenGeneration }}
                - ${{ if eq(parameters.useCLIApply, true) }}:
                  - task: AzureCLI@2
                    displayName: "Terraform Apply via Azure CLI"
                    inputs:
                      azureSubscription: ${{ parameters.AzureRMServiceConnection }}
                      scriptType: bash
                      scriptLocation: inlineScript
                      inlineScript: |
                        echo "Authenticated to Azure via CLI"
                        cd "$(System.DefaultWorkingDirectory)"
                        terraform apply -input=false -auto-approve tfplan
                - ${{ parameters.afterApplySteps }}
      - ${{ parameters.afterDeployJobs }}